### ISSUE TITLE
Tests with no instructions

### ISSUE THREAD

**Issue by ScottDenton** [learn-co-curriculum/fewpjs_array_element_finding#2]
There is nothing about what you need to do to get the tests to pass. Even when reading the test file it only requires a div tag in the html file to pass. Unless I'm missing something obvious, the tests don't appear to have anything to do with the actual subject of the lab.

**Comment by sgharms** [comment]
CUR:

Seems like we should be able to use a tests to exercise this better. Please update.

**Comment by jenmyers** [comment]
I have resolved this by converting into a readme and have made a note to create a new accompanying lab in the near future.
